title: Onur MURAT
description: PhD. Student
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman


author: "Onur MURAT"
url: nrmrt.github.io


github:
  owner_name: Onur MURAT
  owner_url: nrmrt.github.io

githubE:
  owner_name: Onur MURAT

facebook:
  username: alptezbasaran

instagram:
  username: alptezbasaran

email:
  address: onurmurat1991@gmail.com

social:
  name: Alp Tezbasaran
  links:
    - https://twitter.com/alptezbasaran
    - https://www.facebook.com/alptezbasaran
    - https://github.com/nrmrt
