title: Onur MURAT
description: PhD. Student
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman


author: "Onur MURAT"
url: nrmrt.github.io


github:
  owner_name: Onur MURAT
  owner_url: nrmrt.github.io

githubE:
  owner_name: Onur MURAT

facebook:
  username: onur.murat.75

instagram:
  username: nr_mrt

email:
  address: onurmurat1991@gmail.com

social:
  name: Onur MURAT
  links:
    - https://www.facebook.com/onur.murat.75
    - https://github.com/nrmrt
    - https://www.instagram.com/nr_mrt/
